// Code generated by gcraft. DO NOT EDIT.

package testbed

// MockNotifier is a test mock for the Notifier interface.
type MockNotifier struct {
	SendFunc   func(to string, message string) error
	SendCalled int
}

// Send implements Notifier.
func (m *MockNotifier) Send(to string, message string) error {
	m.SendCalled++
	if m.SendFunc != nil {
		return m.SendFunc(to, message)
	}
	return nil
}
