// Package generator produces Go source code from parsed type information.
package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"text/template"

	"github.com/Mahdyaralipor/gcraft/internal/parser"
)

// Options controls which generators are run.
type Options struct {
	Builder  bool
	Mock     bool
	Validate bool
	Clone    bool
}

// DefaultOptions returns Options with everything enabled.
func DefaultOptions() Options {
	return Options{Builder: true, Mock: true, Validate: true, Clone: true}
}

var funcMap = template.FuncMap{
	"isString":    isString,
	"isSlice":     isSlice,
	"funcParams":  funcParams,
	"funcReturns": funcReturns,
	"funcArgs":    funcArgs,
	"zeroReturns": zeroReturns,
}

// Generate runs all enabled generators and returns formatted Go source.
func Generate(ti *parser.TypeInfo, opts Options) (string, error) {
	var body bytes.Buffer
	needsFmt := false

	if ti.IsStruct {
		if opts.Builder {
			code, err := renderBuilder(ti)
			if err != nil {
				return "", fmt.Errorf("builder: %w", err)
			}
			body.WriteString(code)
		}
		if opts.Validate {
			for _, f := range ti.Fields {
				if isString(f.Type) {
					needsFmt = true
					break
				}
			}
			code, err := renderValidator(ti)
			if err != nil {
				return "", fmt.Errorf("validator: %w", err)
			}
			body.WriteString(code)
		}
		if opts.Clone {
			code, err := renderClone(ti)
			if err != nil {
				return "", fmt.Errorf("clone: %w", err)
			}
			body.WriteString(code)
		}
	}

	if ti.IsInterface && opts.Mock {
		code, err := renderMock(ti)
		if err != nil {
			return "", fmt.Errorf("mock: %w", err)
		}
		body.WriteString(code)
	}

	// assemble: header -> imports -> body
	var buf bytes.Buffer
	buf.WriteString("// Code generated by gcraft. DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", ti.Package)
	if needsFmt {
		buf.WriteString("import \"fmt\"\n\n")
	}
	buf.Write(body.Bytes())

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return buf.String(), fmt.Errorf("gofmt failed: %w", err)
	}
	return string(formatted), nil
}

// ── Builder ───────────────────────────────────────────────────────────────────

const builderSrc = `
// {{ .Name }}Builder builds a {{ .Name }} using a fluent API.
type {{ .Name }}Builder struct {
	v {{ .Name }}
}

// New{{ .Name }}Builder returns a new {{ .Name }}Builder.
func New{{ .Name }}Builder() *{{ .Name }}Builder {
	return &{{ .Name }}Builder{}
}
{{ range .Fields }}
// With{{ .Name }} sets the {{ .Name }} field.
func (b *{{ $.Name }}Builder) With{{ .Name }}(v {{ .Type }}) *{{ $.Name }}Builder {
	b.v.{{ .Name }} = v
	return b
}
{{ end }}
// Build returns the constructed {{ .Name }}.
func (b *{{ .Name }}Builder) Build() {{ .Name }} {
	return b.v
}
`

func renderBuilder(ti *parser.TypeInfo) (string, error) {
	tmpl := template.Must(template.New("builder").Funcs(funcMap).Parse(builderSrc))
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, ti); err != nil {
		return "", err
	}
	return buf.String(), nil
}

// ── Validator ─────────────────────────────────────────────────────────────────

const validatorSrc = `
// Validate checks that required string fields of {{ .Name }} are non-empty.
func (v {{ .Name }}) Validate() error {
{{ range .Fields }}{{ if isString .Type }}	if v.{{ .Name }} == "" {
		return fmt.Errorf("{{ $.Name }}.{{ .Name }} is required")
	}
{{ end }}{{ end }}	return nil
}
`

func renderValidator(ti *parser.TypeInfo) (string, error) {
	tmpl := template.Must(template.New("validator").Funcs(funcMap).Parse(validatorSrc))
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, ti); err != nil {
		return "", err
	}
	return buf.String(), nil
}

// ── Clone ─────────────────────────────────────────────────────────────────────

const cloneSrc = `
// Clone returns a shallow copy of {{ .Name }} with slices deep-copied.
func (v {{ .Name }}) Clone() {{ .Name }} {
	c := v
{{ range .Fields }}{{ if isSlice .Type }}	if v.{{ .Name }} != nil {
		c.{{ .Name }} = make({{ .Type }}, len(v.{{ .Name }}))
		copy(c.{{ .Name }}, v.{{ .Name }})
	}
{{ end }}{{ end }}	return c
}
`

func renderClone(ti *parser.TypeInfo) (string, error) {
	tmpl := template.Must(template.New("clone").Funcs(funcMap).Parse(cloneSrc))
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, ti); err != nil {
		return "", err
	}
	return buf.String(), nil
}

// ── Mock ──────────────────────────────────────────────────────────────────────

const mockSrc = `
// Mock{{ .Name }} is a test mock for the {{ .Name }} interface.
type Mock{{ .Name }} struct {
{{ range .Methods }}	{{ .Name }}Func func({{ funcParams .Params }}) ({{ funcReturns .Returns }})
	{{ .Name }}Called int
{{ end }}
}
{{ range .Methods }}
// {{ .Name }} implements {{ $.Name }}.
func (m *Mock{{ $.Name }}) {{ .Name }}({{ funcParams .Params }}) ({{ funcReturns .Returns }}) {
	m.{{ .Name }}Called++
	if m.{{ .Name }}Func != nil {
		return m.{{ .Name }}Func({{ funcArgs .Params }})
	}
	{{ zeroReturns .Returns }}
}
{{ end }}
`

func renderMock(ti *parser.TypeInfo) (string, error) {
	tmpl := template.Must(template.New("mock").Funcs(funcMap).Parse(mockSrc))
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, ti); err != nil {
		return "", err
	}
	return buf.String(), nil
}

// ── helpers ───────────────────────────────────────────────────────────────────

func isString(t string) bool { return t == "string" }
func isSlice(t string) bool  { return len(t) >= 2 && t[:2] == "[]" }

func funcParams(fields []parser.Field) string {
	parts := make([]string, len(fields))
	for i, f := range fields {
		parts[i] = f.Name + " " + f.Type
	}
	return join(parts, ", ")
}

func funcReturns(fields []parser.Field) string {
	parts := make([]string, len(fields))
	for i, f := range fields {
		parts[i] = f.Type
	}
	return join(parts, ", ")
}

func funcArgs(fields []parser.Field) string {
	parts := make([]string, len(fields))
	for i, f := range fields {
		parts[i] = f.Name
	}
	return join(parts, ", ")
}

func zeroReturns(fields []parser.Field) string {
	if len(fields) == 0 {
		return "return"
	}
	parts := make([]string, len(fields))
	for i, f := range fields {
		parts[i] = zeroValue(f.Type)
	}
	return "return " + join(parts, ", ")
}

func zeroValue(t string) string {
	switch t {
	case "string":
		return `""`
	case "bool":
		return "false"
	case "error":
		return "nil"
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"float32", "float64":
		return "0"
	default:
		return "nil"
	}
}

func join(parts []string, sep string) string {
	out := ""
	for i, p := range parts {
		if i > 0 {
			out += sep
		}
		out += p
	}
	return out
}
