// Code generated by gcraft. DO NOT EDIT.

package main

// MockUserRepository is a test mock for the UserRepository interface.
type MockUserRepository struct {
	FindByIDFunc   func(id int) (*User, error)
	FindByIDCalled int
	FindAllFunc    func() ([]*User, error)
	FindAllCalled  int
	SaveFunc       func(u *User) error
	SaveCalled     int
	DeleteFunc     func(id int) error
	DeleteCalled   int
}

// FindByID implements UserRepository.
func (m *MockUserRepository) FindByID(id int) (*User, error) {
	m.FindByIDCalled++
	if m.FindByIDFunc != nil {
		return m.FindByIDFunc(id)
	}
	return nil, nil
}

// FindAll implements UserRepository.
func (m *MockUserRepository) FindAll() ([]*User, error) {
	m.FindAllCalled++
	if m.FindAllFunc != nil {
		return m.FindAllFunc()
	}
	return nil, nil
}

// Save implements UserRepository.
func (m *MockUserRepository) Save(u *User) error {
	m.SaveCalled++
	if m.SaveFunc != nil {
		return m.SaveFunc(u)
	}
	return nil
}

// Delete implements UserRepository.
func (m *MockUserRepository) Delete(id int) error {
	m.DeleteCalled++
	if m.DeleteFunc != nil {
		return m.DeleteFunc(id)
	}
	return nil
}
