// Code generated by gcraft. DO NOT EDIT.

package main

import "fmt"

// UserBuilder builds a User using a fluent API.
type UserBuilder struct {
	v User
}

// NewUserBuilder returns a new UserBuilder.
func NewUserBuilder() *UserBuilder {
	return &UserBuilder{}
}

// WithID sets the ID field.
func (b *UserBuilder) WithID(v int) *UserBuilder {
	b.v.ID = v
	return b
}

// WithName sets the Name field.
func (b *UserBuilder) WithName(v string) *UserBuilder {
	b.v.Name = v
	return b
}

// WithEmail sets the Email field.
func (b *UserBuilder) WithEmail(v string) *UserBuilder {
	b.v.Email = v
	return b
}

// WithAge sets the Age field.
func (b *UserBuilder) WithAge(v int) *UserBuilder {
	b.v.Age = v
	return b
}

// WithTags sets the Tags field.
func (b *UserBuilder) WithTags(v []string) *UserBuilder {
	b.v.Tags = v
	return b
}

// WithIsActive sets the IsActive field.
func (b *UserBuilder) WithIsActive(v bool) *UserBuilder {
	b.v.IsActive = v
	return b
}

// Build returns the constructed User.
func (b *UserBuilder) Build() User {
	return b.v
}

// Validate checks that required string fields of User are non-empty.
func (v User) Validate() error {
	if v.Name == "" {
		return fmt.Errorf("User.Name is required")
	}
	if v.Email == "" {
		return fmt.Errorf("User.Email is required")
	}
	return nil
}

// Clone returns a shallow copy of User with slices deep-copied.
func (v User) Clone() User {
	c := v
	if v.Tags != nil {
		c.Tags = make([]string, len(v.Tags))
		copy(c.Tags, v.Tags)
	}
	return c
}
